[project]
name = "libvirt-mcp"
version = "0.1.0"
description = "MCP server for Libvirt"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "libvirt-python>=11.3.0",
    "mcp[cli]>=1.7.1",
]
